language: php
php:
  - 7.3

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

install:
  - composer update $DEFAULT_COMPOSER_FLAGS
  - cp phpunit.xml.dist phpunit.xml

script:
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success:
  # https://github.com/codecov/codecov-python/issues/158 or https://github.com/mapbox/mapbox-gl-native/issues/15095
  - bash <(curl -s --connect-timeout 300 --max-time 330 --retry 5 --retry-delay 5 https://codecov.io/bash)

notifications:
  email: true