language: php
php:
  - 7.3

env:
  global:
    - CODECOV_TOKEN="328c9a87-3c83-4755-8e7d-78ae585399ef"
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

install:
  - composer update $DEFAULT_COMPOSER_FLAGS
  - cp phpunit.xml.dist phpunit.xml

script:
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
