services:
    Fincallorca\DateTimeBundle\EventListener\Initializer:
        class: Fincallorca\DateTimeBundle\EventListener\Initializer
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request,  method: updateDateTimeKernel }
            - { name: kernel.event_listener, event: console.command, method: updateDateTimeKernel }